name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: wifi-speaker
            asset_name: wifi-speaker-linux
          - os: windows-latest
            artifact_name: wifi-speaker.exe
            asset_name: wifi-speaker-windows.exe
          - os: macos-latest
            artifact_name: wifi-speaker
            asset_name: wifi-speaker-macos

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get install libasound2-dev
        if: matrix.os == 'ubuntu-latest'
      - name: Build
        run: cargo build --release --locked
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
